config/routes.rb
Rails.application.routes.draw do
  root "departments#index"
  #resources :controller - creates routes for you via rails
   resources :departments do  
   resources :shoes
  end 

  resources :shoes do
    resources :comments
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  before_save :check_author
  belongs_to :shoe

  def check_author
    if self.author.blank?
      self.author = 'anon'
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :shoes, dependent: :destroy
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :department
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_shoe

  def new
    @comment = Comment.new
  end

  def create
    @comment = @shoe.comments.new(comment_params)
    if @comment.save
      redirect_to department_shoe_path(@shoe.department_id, @shoe)
    else
      render :new
    end 
  end
  
  private
    def set_shoe
      @shoe = Shoe.find(params[:shoe_id])
    end
    
    def comment_params
      params.require(:comment).permit(:body, :author)
    end  
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @departments = Department.all
    #render :index
  end

  def show
    #localhost:3000/subs/1 or :id
    # @sub = Sub.find(params[:id])
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end  
  end  

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      #update(key:value) key = name: value = params[:sub][:name]
      #example { :id 1, name: "Spencer"}

      # redirect_to sub_path(@sub)
      redirect_to @department #same as above - simplified code
    else
      render :edit
    end  
  end
  
  def destroy
    @department.destroy
    redirect_to department_path
  end

  private
  def set_department
    @department = Department.find(params[:id])
  end

    def department_params
      params.require(:department).permit(:name)
    end   

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_department
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  def index
    @shoes = @department.shoes
  end

  def show
  end

  def new
    @shoe = @department.shoes.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @shoe = @department.shoes.new(shoe_params)

    if @shoe.save
      redirect_to [@department, @shoe]
    else
      render :new
    end
  end

  def update
    if @shoe.update(shoe_params)
      redirect_to [@department, @shoe]
    else
      render :edit
    end
  end

  def destroy
    @shoe.destroy
    redirect_to department_shoes_path
  end

  private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    def shoe_params
      params.require(:shoe).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></p>
</hr>

app/views/comments/new.html.erb
<h1>Add a comment</h1>
<%= form_for [@shoe, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: 'Leave Blank To Remain Anonymous' %>
  <br />
  <%= f.submit %>
  <% end %>

app/views/departments/_form.html.erb
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1>Check Out Our Shoes!</h1>
<%= link_to 'Create a new department', new_department_path %>
<ul>
  <% @departments.each do |department| %>
    <li><%= link_to department.name, department_path(department) %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Department', department_shoes_path(@department) %>
<br />
<%= link_to 'Edit Department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %>

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path %>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shoes/_form.html.erb
<h1><%= @shoe.id ? 'Edit Shoe' : 'Create Shoe' %></h1>
<hr />
<%= form_for [@department, @shoe] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/shoes/edit.html.erb
<h1>Shoes#edit</h1>
<p>Find me in app/views/shoes/edit.html.erb</p>

app/views/shoes/index.html.erb
<h1>Click a Shoe To View Content</h1>
<%= link_to 'Create a new shoe', new_department_shoe_path(@department) %>
<ul>
  <% @shoes.each do |shoe| %>
    <li><%= link_to shoe.name, [@department, shoe] %></li>
  <% end %>
</ul>

app/views/shoes/new.html.erb
<h1>Shoes#new</h1>
<p>Find me in app/views/shoes/new.html.erb</p>

app/views/shoes/show.html.erb
<h1><%= @department.name %> - <%= @shoe.name %></h1>
<p><%= @shoe.body %></p>
<h2>Comments</h2>

<% @shoe.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
<% end %>

<hr />

<%= link_to 'Add Comment', new_shoe_comment_path(@shoe) %>
</br>
<%= link_to 'Edit Shoe', edit_department_shoe_path([@department, @shoe]) %>
</br>
<%= link_to 'Delete Shoe', [@department, @shoe], method: :delete %>
</br>
<%= link_to 'Back To Shoes', department_shoe_path(@department) %>